### ISSUE TITLE
how do you use the prefix to generate caption?

### ISSUE THREAD

**Issue by KN1GHT9** [ml-jku/semantic-image-text-alignment#1]
When you use Llama to generate capiton, how do you use prefix? 
Do you construct a prompt containing prefix word?

**Comment by paischer101** [comment]
For Llama we retrieve the top-k tokens, interleave them with spaces, and append the prompt "A picture of "
You can find the exact procedure [here](https://github.com/ml-jku/semantic-image-text-alignment/blob/main/semantic_image_text_alignment/generate_captions.py).
